### ISSUE TITLE
segfault when changing profile

### ISSUE THREAD

**Issue by zetok** [krepa098/qTox#8]
a2cf91cb364e786e6e252fbd957607ba7462f50f

https://gist.github.com/zetok/b0405474732d22850965

**Comment by zetok** [comment]
I still managed to segfault it on 535757670b389a247f33204056f0ad5da5f63a55: https://gist.github.com/zetok/b875b0b7f2a5c7a3dc9a

**Comment by dubslow** [comment]
Yikes that's a doozy bt.

Also:
>QGraphicsScene::removeItem: item 0x555556465330's scene (0x5555564616f0) is different from this scene (0x555556463880)

**Comment by krepa098** [comment]
> https://gist.github.com/zetok/b875b0b7f2a5c7a3dc9a

OfflineMsgEngine doesn't get destroyed upon switching profiles, hence the invalid friend id.
